spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://gpu1.dev.cn1.corp.agrant.cn:3306/testout?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: outtest
    password: 123456
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  logging:
    level:
      root: info
      com.cribbee: debug
    file: log/gofree-dev.log