spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbgf?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: dengdaiwushi
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  logging:
    level:
      root: info
      com.cribbee: debug
    file: log/gofree-dev.log