spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.230.168.143:3306/gofree?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: BNU_lxy123
  jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      database-platform: com.cribbee.gofree.util.MysqlConfig
  logging:
    level:
      root: info
      com.cribbee: debug
    file: log/gofree-dev.log